const menuData = [
    { id: 1, name: "凉拌黄瓜", price: 18, desc: "爽脆可口，蒜香扑鼻，开胃首选", category: "凉菜", emoji: "🥒" },
    { id: 2, name: "口水鸡", price: 28, desc: "麻辣鲜香，红油浸润，回味无穷", category: "凉菜", emoji: "🐔" },
    { id: 3, name: "蒜泥白肉", price: 32, desc: "薄切五花，蒜香浓郁，经典川味", category: "凉菜", emoji: "🥩" },
    { id: 4, name: "皮蛋豆腐", price: 22, desc: "嫩滑豆腐配松花蛋，清爽宜人", category: "凉菜", emoji: "🥚" },
    { id: 5, name: "宫保鸡丁", price: 38, desc: "花生与鸡丁的经典碰撞，麻辣鲜甜", category: "热菜", emoji: "🌶️" },
    { id: 6, name: "麻婆豆腐", price: 28, desc: "麻辣鲜香嫩烫酥，川菜灵魂之作", category: "热菜", emoji: "🫘" },
    { id: 7, name: "红烧肉", price: 48, desc: "肥而不腻，入口即化，浓油赤酱", category: "热菜", emoji: "🍖" },
    { id: 8, name: "鱼香肉丝", price: 36, desc: "酸甜微辣，鱼香四溢，下饭神器", category: "热菜", emoji: "🥢" },
    { id: 9, name: "清蒸鲈鱼", price: 68, desc: "鲜活鲈鱼清蒸，保留原汁原味", category: "热菜", emoji: "🐟" },
    { id: 10, name: "糖醋里脊", price: 42, desc: "外酥里嫩，酸甜可口，老少皆宜", category: "热菜", emoji: "🍗" },
    { id: 11, name: "米饭", price: 3, desc: "东北珍珠米，粒粒饱满", category: "主食", emoji: "🍚" },
    { id: 12, name: "蛋炒饭", price: 18, desc: "金包银蛋炒饭，粒粒分明", category: "主食", emoji: "🍛" },
    { id: 13, name: "担担面", price: 22, desc: "芝麻酱香浓郁，麻辣鲜香", category: "主食", emoji: "🍜" },
    { id: 14, name: "水饺", price: 28, desc: "手工现包，皮薄馅大，鲜美多汁", category: "主食", emoji: "🥟" },
    { id: 15, name: "可乐", price: 8, desc: "冰镇可口可乐，畅爽怡神", category: "饮品", emoji: "🥤" },
    { id: 16, name: "雪碧", price: 8, desc: "清爽柠檬味，冰凉透心", category: "饮品", emoji: "🥤" },
    { id: 17, name: "酸梅汤", price: 12, desc: "古法熬制，酸甜解腻", category: "饮品", emoji: "🧉" },
    { id: 18, name: "青岛啤酒", price: 15, desc: "冰镇青岛纯生，麦香浓郁", category: "饮品", emoji: "🍺" },
    { id: 19, name: "西红柿蛋汤", price: 18, desc: "酸甜开胃，家常味道", category: "汤品", emoji: "🍅" },
    { id: 20, name: "紫菜蛋花汤", price: 15, desc: "清淡鲜美，暖胃舒心", category: "汤品", emoji: "🌊" },
    { id: 21, name: "酸辣汤", price: 20, desc: "酸辣浓郁，暖身驱寒", category: "汤品", emoji: "🥣" },
];